### ISSUE TITLE
Use with Azure Storage Explorer

### ISSUE THREAD

**Issue by jamesrichford** [arafato/azurite#155]
I'm trying to user Microsoft Azure Storage Explorer to check out the contents but the loading wheels keep spinning :(

![image](https://user-images.githubusercontent.com/8244919/35876446-3a1fd0d0-0b6a-11e8-9b73-b5586de861ac.png)

Do you need to do any special setup to get it working?

**Comment by jamesrichford** [comment]
Interestingly just got an error:

![image](https://user-images.githubusercontent.com/8244919/35876553-845bdefa-0b6a-11e8-9ec2-eae1af4bea3a.png)

This may be a problem with the explorer but just wanted to see if anyone had used it in conjunction with Azurite / had any tips or alternative tools to view queues etc.

**Comment by jamesrichford** [comment]
right, it appears that it's just very slow/error prone... no idea why though do we think it's worth investigating? Is this a tool we want to be supporting?

**Comment by arafato** [comment]
hi @jamesrichford ! I think there are three problems with the MS Azure Storage Explorer Tool currently:
- It cannot be configured to use a different emulator per default. Meaning whenever you unfold the Local Storage Account item it tries to start the official storage emulator. Depending on whether another process is already listening on ports 10000-10004 this may cause strange behavior of the explorer (see next point). 
- The slow/error prone behavior may be because of Storage Explorer trying to constantly launch the official emulator which fails in case Azurite is already listening on port 10000 for example. Maybe there is a special handshake between storage explorer and official emulator first?
- Storage Explorer does not support a local emulator at all on platforms other than Windows.

I've already tried to address these issues at the product group but they have a lot of different things on their roadmap which have a higher priority. I will get back to them and ask about the current state. Will post an update here asap.

**Comment by arafato** [comment]
It seems that Storage Explorer expects the $logs container to be present in the storage account. It does an initial HEAD operation on the $logs container. If this operation returns a 404 Storage Explorer is stuck for over a minute or so. If the container exists everything seems to be way faster. I cannot find anything in the documentation, however, that says that a $logs container must be present...

**Comment by jamesrichford** [comment]
@arafato so a `HEAD` call to `$logs` on an actual Azure Storage Account returns 404?

Is it the case we just need to implement these end points then I guess?

**Comment by arafato** [comment]
@jamesrichford well a `HEAD` call to a non-existant `$logs` container returns 404 on Azurite as well. But this is exactly where Storage Explorer gets stuck. If I add a `$logs` container and it returns 200 everything works fine. I need to capture the traffic with Fiddler and see how Storage Explorer behaves with Azure Emulator or real Storage Accounts.

**Comment by arafato** [comment]
@jamesrichford during initialization time Azurite now creates a `$logs` container (if the workspace / json file does not exist yet). This improves integration with Azure Storage Explorer. 

@seguler can you provide an update about the future roadmap of Azure Storage Explorer integration with Azurite?

**Comment by jamesrichford** [comment]
Ace thanks @arafato :) congrats on 100 stars by the way!

Looking forward to much more awesome stuff, may even be submitting some PRs soon. Is table storage the top of your agenda?

**Comment by arafato** [comment]
@jamesrichford thanks! :-)
Yes, table storage has highest priority for me right now. Aiming for a complete implementation by the end of March at the very latest.
Looking forward to your PRs, really appreciating your commitment here, thanks!
