### ISSUE TITLE
Run azurite using pm2

### ISSUE THREAD

**Issue by waygee** [arafato/azurite#56]
Is it possible to run azurite using pm2 process manager for nodejs?  

I would like to do something like:

cd /dir/where/azurite
pm2 start someprocess.js

Thanks for your help in advance.

**Comment by arafato** [comment]
Good point @waygee ! I do not see a reason why pm2 should not work with Azurite. There are two points, however, that need to be considered IMHO:
- executing Azurite on multiple cores (resulting in multiple processes) can lead to race conditions since it is not stateless. Azurite stores metadata in an in-memory database which is persisted every 5 seconds to disk.
- graceful shutdown is not supported yet as `SIGINT` is not intercepted yet. Happy to add support for that.

Thoughts?

**Comment by waygee** [comment]
Thanks for your response @arafato, in regards to the issues you raise:

I intend to run Azurite in a single thread (in forked mode in pm2), so I believe I can get by with the first limitation.

In addition, I am intending to use Azurite in a vagrant virtual machine for dev/testing purposes so I think it would be ok to not have graceful shutdown right away.  Thank you for considering to add support for graceful shutdown, it would be very welcome.

I originally opened the issue to get the correct command line syntax for starting azurite using pm2.  Can you help supply the actual command that I would need to run?

**Comment by arafato** [comment]
Assuming that Azurite has beed installed globally with `$ npm install -g azurite`, you can run it with `pm2` as follows:
Under Linux you can simply start it with `$ pm2 start azurite`.
Under Windows there seems to be a bug with starting globally installed packages. See [https://github.com/Unitech/pm2/issues/2037](https://github.com/Unitech/pm2/issues/2037) for details. This also affects Azurite.

You can, however, install it locally into some folder. Assuming that we are in `c:\\local\folder`, execute the following steps:
You install it locally with 
`npm install azurite`
`cd node_modules\azurite`
`pm2 start bin\azurite`

I've also just added support for graceful shutdown. Will be published in the next few days as v0.7.10.

**Comment by arafato** [comment]
@waygee just published `v0.7.10` which brings support for graceful shutdown for PM2.
