### ISSUE TITLE
Handle edge-case blob names

### ISSUE THREAD

**Issue by s-ol** [arafato/azurite#57]
A blob with a trailing slash (`blob/name/`) for example causes an error:

    `{ [StorageError: EISDIR: illegal operation on a directory, open '/opt/azurite/__blobstorage__/container/blob/name/'] }`

MS Azure stores this properly because their directories are just a virtual filtering system on top of a flat storage scheme. A quick fix would be to add a file with a fixed name like `blob/name/.INDEX_BLOB` (which of course has the drawback of reserving that name).

That wouldn't properly handle names with multiple trailing slashes though I think, so maybe a Suffix/slash replacement could be added instead so that `blob/name/` becomes the file `blob/name$SLASH`  and `blob/name///` becomes `blob/name$SLASH$SLASH$SLASH`.

**Comment by arafato** [comment]
Thanks @s-ol for finding this bug! Here are my thoughts on how such a call should be actually processed:

I think that a PUT Blob call to a path with a trailing / should result in a NOOP. Virtual dirs solely exist on an SDK / Client level and serve only as a prefix of a blob name. As long as no actual blob is created with that prefix there is no need to create anything on the server side. This is also backed by the way how 
Storage Emulator and our SDKs work: creation of a virtual dir (without any blobs in it) do not send any call to the backend.

What do you think?

**Comment by s-ol** [comment]
@arafato I think behaviour should match azure blob storage, to which a blobId is just an identifier and path segments are used only in the maintenance UI and when enumerating paths afaik.

**Comment by arafato** [comment]
@s-ol you are absolutely right, I just validated with how Azure Blob Storage works when using trailing slashes. In order to not reserve any special characters or words for these kinds of blob names (such as `blob/name/$SLASH` or `blob/name/.INDEX_BLOB` as you suggested) I will store the names of these blobs just as is in the in-memory database (e.g. as `some/blob///`) and reference them internally to a special dedicated disk folder (which is not visible from the outside) where they will carry a random GUID. Will provide an according fix hopefully in the next few days. Will be published with `v0.7.10`.

**Comment by s-ol** [comment]
cool. i was thinking​ of a clean way to eliminate the special name thing but i didn't know azurites internals.

**Comment by arafato** [comment]
@s-ol just published `v0.7.10`. Let me know if it does not work you. In this case please re-open this issue.
